# Generated by Django 3.2.25 on 2024-04-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20240423_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='helpful_count',
        ),
        migrations.RemoveField(
            model_name='review',
            name='not_helpful_count',
        ),
    ]
