# Generated by Django 3.2.25 on 2024-04-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='notify_post',
            new_name='notify_on_new_post',
        ),
    ]
