# Generated by Django 3.2.25 on 2024-04-20 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
